spring:
  datasource:
    url: jdbc:postgresql://localhost:6432/bayzdelivery
    username: postgres
    password: harshit
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml

server:
  port: 8081
  servlet:
    context-path: /api
